### ISSUE TITLE
Error creating result-DataFrame in the outputlib

### ISSUE THREAD

**Issue by uvchik** [oemof/oemof#69] opened 2016-01-26 14:57 UTC
There is an error using the default example (storage_invest.py).

```python
Traceback (most recent call last):
  File "/home/uwe/rli-lokal/git_home/oemof_base/examples/storage_optimization/storage_invest.py", line 201, in <module>
    exclude_obj_uids=['pv'])
  File "/home/uwe/rli-lokal/git_home/oemof_base/oemof/outputlib/to_pandas.py", line 232, in plot_bus
    subset = subset.unstack(level='obj_uid')
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py", line 3605, in unstack
    return unstack(self, level)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/reshape.py", line 398, in unstack
    return _unstack_frame(obj, level)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/reshape.py", line 438, in _unstack_frame
    value_columns=obj.columns)
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/reshape.py", line 98, in __init__
    self._make_selectors()
  File "/usr/local/lib/python3.4/dist-packages/pandas/core/reshape.py", line 136, in _make_selectors
    raise ValueError('Index contains duplicate entries, '
ValueError: Index contains duplicate entries, cannot reshape
```

**Comment by simonhilpert** [comment] 2016-01-26 15:25
@s3pp @ckaldemeyer can you adapt the example_app.py on the outputlib as well? 

I think there would be an error two. In my apps i am missing inputs in the electrical bus from 
chp units (or general inputs in el. bus)

**Comment by ckaldemeyer** [comment] 2016-01-27 09:36
It is caused by the new (dict based and faster) method to create the dataframe. We are working on it and will find a solution!

**Comment by ckaldemeyer** [comment] 2016-01-27 09:37
Therefore we have created the branch *features/fix-outputlib*

**Comment by ckaldemeyer** [comment] 2016-01-27 09:40
@uvchik @simonhilpert : Does it make sense to revert the dev-Branch to "47d7779c2b7dd8295d9b0043b02905e78499197f" before Martins merge? 

After that, Uwe has only made one commit with some PEP8 adjustments.

**Comment by s3pp** [comment] 2016-02-04 15:31
Bug was resolved by @ckaldemeyer

**Closed by s3pp** 2016-02-04 15:31 UTC
Labels: bug
