### ISSUE TITLE
New custom component for Demand Side Management

### ISSUE THREAD

**Issue by nailend** [oemof/oemof#622] opened 2019-06-27 13:07 UTC
#### Dear oemof dev(_elopment_)-com(_unity_),

Within the Windnode-Project, we are about to develop a new custom component addressing the implementation of "Demand-Side-Management (DSM)" in _oemof_. 

Due to the rising shares of renewables in the grid and the german market design, production flexibility has high costs. Therefore solving the issue on the counterside by demand side flexibility comes to the fore. Shifting load capacities for a certain amount of time will be used for peak load shaving or to smoothen load curves.

W. Schill & A. Zerrahn (DIW) already proposed an alternative formulation in 

> Alexander Zerrahn, Wolf-Peter Schill: 
On the Representation of Demand-Side Management in Power System Models 
[Energy 84 (2015), S. 840-845] [see here: DIW ](https://www.diw.de/sixcms/detail.php?id=diw_01.c.503717.de)

which they implemented in the GAMS-tool "_DIETER_" 

As the formulation is promising, we will follow the path and seek for further development. Any kind of contribution is warmly welcomed.

Regards
Julian
Student assistant at RLI 
Windnode Project @gplssm

**Comment by uvchik** [comment] 2019-06-27 15:52
Hi Jul(ian) :smirk: 

I think there are different ways to implement this.

1. A new shiftable demand class, which can be used instead of a sink
2. A new shift-storage class, which can be added to the electricity bus
3. An extension to the Flow class (shiftable flow), which can be used in the Flow to the sink
4. An extension to the GenericStorage, to allow negative charge and time limits.

I may have forgotten an option.

What do you have in mind?

**Comment by gplssm** [comment] 2019-06-28 13:56
I'm happy about your feedback, @uvchik :clap: 

And thanks for providing suggestions where to subclass from! From what I know at the moment, proposal (1) seems to be the best idea. We'll pursue this idea for now.

A quick disclaimer: we won't too fast. First, we need to understand how to extend the model's constraints by implementing a new custom component. Both of us aren't too familiar with Pyomo... We'll come back with intermediate results and, most likely questions too, soon.

**Comment by p-snft** [comment] 2019-07-01 03:37
This is a really interesting topic. Until now, we helped ourselves with storages. Actually, they do not need to be allowed to have a negative storage level: As long as they are big enough, a high initial storage level will do the trick. However, assume that demands can be shifted by one time step, so it should be forced to reach the same storage level every other time step. Until now, we neglected this part. Instead, we drafted an individual sink which is hidden behind a storage with a time-varying usable capacity (of the next time steps' demand). I am looking forward to having something more elaborate and will be glad to help.

**Comment by nailend** [comment] 2019-07-18 16:44
Hey there, 

this is our concept:
![Konzept_class](https://user-images.githubusercontent.com/51374526/61474904-e5a63700-a989-11e9-8a77-efc4235a4ceb.jpg)

We do want to modify a **class sink**  as **subclass sink dsm** inheriting from oemof/network/sink:

![Konzept_flow](https://user-images.githubusercontent.com/51374526/61474705-7597b100-a989-11e9-87da-e14af0161dfb.jpg)

Therefore we need to access the pyomo.variable created by the solph.flow() to constrain it with the demand equation. I wasn't yet able to find out how this is possible or whether it is at all?! GenericStorage does it the same way, doesn't it?

Is there anyone able to navigate through the structures of oemof and can provide some help?


Thanks a lot :)

**Comment by simnh** [comment] 2019-07-19 09:03
You can find/use the variable of the Flow `m.flow[from, to, timestep]`, where m is the pyomo optimization model. You will have to create a pyomo.block for oemof.solph.components for example to work with our logic. 

Inside this class you can create the Variables (Demand up/down) and also add constraints where all parameters and variables are combined as required. 

It woul generally be easy to copy something like the `ExtractionTurbineCHP` class and its associated pyomo block class `ExtractionTurbineCHPBlock`, rename and adapt. 

Once you are in the block with your variables everything is pyomo logic. 

Great Improvement!!

**Comment by gplssm** [comment] 2019-07-19 22:11
Thanks for the suggestion, @simnh 

I've tried the proposed and had a look into `ExtractionTurbineCHP` and the corresponding Block.

To try out how the flow between the electricity bus and the SinkDSM can be linked to the internally calculated demand of the SinkDSM, I've modified the prototyping script in the WindNODE repo.
https://github.com/windnode/DSM_modelling_prototype/blob/reduced_model/main_dsm_sink_test.py

In order to have a quick test case, I mocked the normal Sink by linking the flow directly to the demand time series. Here's a comparison.

![Bildschirmfoto_2019-07-19_23-32-25](https://user-images.githubusercontent.com/8255114/61567680-bf16f780-aa80-11e9-824e-78f8eb3d82d1.png)

@nailend could you please pick it up, include the other constraints and include the dsm_up/dsm_down in the `input_output_relation_rule()`?

**Comment by nailend** [comment] 2019-08-15 15:31
Hey, 
meanwhile we managed to implement the component , just as we had planned. You can find the component here: [oemof_DSM_component.py](https://github.com/windnode/DSM_modelling_prototype/blob/master/oemof_DSM_component.py)
test energy system here: [oemof_dsm_test.py](https://github.com/windnode/DSM_modelling_prototype/blob/master/oemof_dsm_test.py)
and test data set here: [oemof_dsm_test_data.csv](https://github.com/windnode/DSM_modelling_prototype/blob/master/oemof_dsm_test_data.csv)

Unfortunately we discovered a problem which is allowed by the constraint (10).

If the useful potential for DSMup or DSMdown is less than the corresponding capacity, the model can use the rest to artificially extend the set delay time. If you only use half of the capacity for both DSMup and DSMdown the delay time can become infinite. As shown in the following graph. The delay time L = 2 was set.
![oemof_dsm](https://user-images.githubusercontent.com/51374526/63105180-8fc0b100-bf80-11e9-949d-f8fd697f6614.png)

Therefore we need to replace equation 10 by something which only allows one variable, either DSMup or DSMdown, to become greater than zero. 
Does anyone have an Idea for a workaround or experience how to solve this while keeping it a linear problem ?
Looking forward to your ideas.

**Comment by p-snft** [comment] 2019-08-20 12:22
One could solve this by introducing two binary status variables and require their sum to be limited to 1. This option would be easy to understand but bad in terms of computational performance, as it would create a non-convex integer problem. I have started something using that idea in #623.

Secondly, one could reformulate the problem in a way that the compensation has to be done (not started) after some time delay `t_{delay}`: `\sum_{i=t}^{t+t_{delay}} [c_{up}(i)+c_{do}(i)] = 0`. I did not fully think this through, however. It might also be rather costly in terms of performance. To eliminate some of the overhead, one could eliminate the different variables for DSM up and down. Instead, one would use a (possibly negative) variable `dsm` with `-DSMdo < dsm <DSMup`.

(I am thinking about a third option which would include derived variables with bounds and might be faster.)

**Comment by gplssm** [comment] 2019-08-23 16:06
@p-snft thanks for your input!

Some comments to your proposals

1. We would really like to avoid introducing binary variables because of computational performance. So I put this option on hold
2. I guess you were referring to `DSM^up_t` and `DSM^do_tt`. 
  Without thinking it to the very end, I would say such a constraint would introduce another rolling time frame where within `DSM^up_t` and `DSM^do_tt` are set into relation. It might prevent both variables being active (meaning > 0) at the same time, but I think it would introduce other artifacts. Let's assume `t_delay` is 24. There might be a time frame of 24 time steps where DSM is in action and the balance is true. Going one or multiple time steps forward (and assuming the next 24 time steps no DSM is planned) , another imbalance is created the requires DSM being in action again and compensating for DSM that was already compensated before.
3. I tried a formulation with a single variable for `DSM^up_t` and `DSM^do_tt`. Sadly, no success. It created a chain of constraints which would force to compensate for DSM action twice.

I appreciate your thoughts a lot! Beginning of next week I'll discuss again with my colleagues and we'll come back in this issue.

**Comment by p-snft** [comment] 2019-08-26 06:53
> We would really like to avoid introducing binary variables because of computational performance. So I put this option on hold

I really appreciate this. Often, throwing computational time at problems is not the best option.

>  Without thinking it to the very end, I would say such a constraint would introduce another rolling time frame where within `DSM^up_t` and `DSM^do_tt` are set into relation. It might prevent both variables being active (meaning > 0) at the same time, but I think it would introduce other artifacts. Let's assume `t_delay` is 24. There might be a time frame of 24 time steps where DSM is in action and the balance is true. Going one or multiple time steps forward (and assuming the next 24 time steps no DSM is planned) , another imbalance is created the requires DSM being in action again and compensating for DSM that was already compensated before.

They would still be allowed to be active at the same time, but that would have no benefit, so it should not happen. According the artefacts: It would label compensating DSM a DSM into the other direction. But I do not see why this would be a problem. After all, time-shifting the demand is characterized by the combination of the two sides.

> I tried a formulation with a single variable for `DSM^up_t` and `DSM^do_tt`. Sadly, no success. It created a chain of constraints which would force to compensate for DSM action twice.

Did you adjust the integral energy? If you take e.g.  `demand-DSM_do` your "no DSM" power level, the average DSM should now be `DSM_do > 0`.

**Comment by uvchik** [comment] 2019-08-26 07:34
I think it is not only a question of binary variables. In my opinion it is wrong to forbid up and down at the some time. It could also be a strategy, that different devices shift their demand one after the other. This could lead to your picture above. The problem is, that the solver does not know enough about your demand structure so you have to check afterwards whether the results are realistic or not.

**Comment by gplssm** [comment] 2019-08-27 16:13
> I think it is not only a question of binary variables. In my opinion it is wrong to forbid up and down at the some time. It could also be a strategy, that different devices shift their demand one after the other. This could lead to your picture above. The problem is, that the solver does not know enough about your demand structure so you have to check afterwards whether the results are realistic or not.

 This is exactly true! Today, we agreed for the project WindNODE to accept that DSM_up and DSM_do can take effect at the same time, with the rationale explained by @uvchik 
We try to construct some test cases that show validity of this approach. 

> Did you adjust the integral energy? If you take e.g. demand-DSM_do your "no DSM" power level, the average DSM should now be DSM_do > 0.

Sorry, I do not understand you question :-/ 

We'll come back, when we have new ideas. I hope we can come back with a ready-to-merge PR soon ;-)

**Comment by p-snft** [comment] 2019-08-28 05:10
If you define DSM in a way that DSM_up and DSM_do may be active at the same time, my suggestions do not make any sense at all. I thought it should model shifting demands in time only. (In this picture, you shift demand from one point in time to another one. Then, DSM_up and DSM_do may not overlap.)

**Comment by uvchik** [comment] 2019-08-28 07:16
In my opinion both cases make sense, so in the long run it would be nice to have both options (allow/forbid up and down at the same time). But I would encourage you to start with the simple implementation and we can add everything else later on.

A DSM object that represents different option in e.g. a region should accept up/down at the same time. A small offgrid system with a few components should be able to add a single device DSM with no up/down at the same time.



> We'll come back, when we have new ideas. I hope we can come back with a ready-to-merge PR soon ;-)

:+1: Thanks in advance :smirk:

**Comment by nailend** [comment] 2019-11-12 18:21
thanks a lot for supporting and merging the component!

using the component @gplssm  and me just  realized an error by design as soon as it comes to the costs of the component.

As with the other components, I would use the "variable_costs". This assigns costs to the flow of the SinkDSM. As stated in the [equation 1](https://oemof.readthedocs.io/en/latest/api/oemof.solph.html#oemof.solph.custom.SinkDSMDelayBlock)  of either "interval" and "delay" method, the flow represents the whole income flow from the electricity bus to the SinkDSM. This includes ALL generation. 


If the cost would be assigned to the variable DSMup/DSMdown/DSMupdown the peaks at hour 8h and 17h in the lower subplot wouldn't appear. 
![flow_costs](https://user-images.githubusercontent.com/51374526/68698128-85628300-0580-11ea-9322-147a12614af7.jpg)

We would propose to assign cost directly to DSMup/DSMdown/DSMupdown. But these decision variables are internal to SinkDSM and cant be accessed via variable costs.
@uvchik could you help us to find a way how to assign variable cost directly to these variables? We assume it requires some more hacking, which might involve to use Pyomo directly.

If anything is unclear, feel free to call @gplssm

**Comment by gplssm** [comment] 2019-11-21 08:42
Closed in favor of #655

**Closed by gplssm** 2019-11-21 08:42 UTC
Labels: enhancement, feedback wanted, oemof-solph
